/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class li_testcamera_JniUtil */

#ifndef _Included_li_testcamera_JniUtil
#define _Included_li_testcamera_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     li_testcamera_JniUtil
 * Method:    testmain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_li_testcamera_JniUtil_testmain
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
